USE TTNNDB
GO

ALTER TABLE PHIEUGIAHAN
ADD
	CONSTRAINT FK_PHIEUGIAHAN_PHIEUDANGKY
	FOREIGN KEY (MADANGKY)
	REFERENCES PHIEUDANGKY(MAPHIEUDANGKY)
	ON DELETE SET NULL,

	CONSTRAINT FK_PHIEUGIAHAN_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL
GO

ALTER TABLE CHUNGMINHGIAHAN
ADD
	CONSTRAINT FK_CHUNGMINHGIAHAN_PHIEUGIAHAN
	FOREIGN KEY (MAPHIEUCM)
	REFERENCES PHIEUGIAHAN(MAPHIEUGIAHAN)
	ON DELETE NO ACTION
GO

ALTER TABLE PHIEUDANGKY
ADD
	CONSTRAINT FK_PHIEUDANGKY_KHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL,

	CONSTRAINT FK_PHIEUDANGKY_LICHTHI
	FOREIGN KEY (MALICHTHI)
	REFERENCES LICHTHI(MALICHTHI)
	ON DELETE SET NULL,

	CONSTRAINT FK_PHIEUDANGKY_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
GO

ALTER TABLE LICHTHI
ADD
	CONSTRAINT FK_LICHTHI_PHONGTHI
	FOREIGN KEY (MAPHONG)
	REFERENCES PHONGTHI(MAPHONG)
	ON DELETE SET NULL,

	CONSTRAINT FK_LICHTHI_LOAIDANHGIANANGLUC
	FOREIGN KEY (MADANHGIA)
	REFERENCES LOAIDANHGIANANGLUC(MADANHGIA)
	ON DELETE SET NULL,

	CONSTRAINT FK_LICHTHI_DONVICHAMTHI
	FOREIGN KEY (MADONVI)
	REFERENCES DONVICHAMTHI(MADONVI)
	ON DELETE SET NULL
GO

ALTER TABLE PHIEUDUTHI
ADD
	CONSTRAINT FK_PHIEUDUTHI_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL,

	CONSTRAINT FK_PHIEUDUTHI_THISINH
	FOREIGN KEY (MATHISINH)
	REFERENCES THISINH(MATHISINH)
	ON DELETE SET NULL
GO

ALTER TABLE LOAIDANHGIANANGLUC
ADD
	CONSTRAINT FK_LOAIDANHGIANANGLUC_LINHVUC
	FOREIGN KEY (MALINHVUC)
	REFERENCES LINHVUC(MALINHVUC)
	ON DELETE SET NULL
GO

ALTER TABLE CHUNGCHI
ADD
	CONSTRAINT FK_CHUNGCHI_KHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL,

	CONSTRAINT FK_CHUNGCHI_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL,

	CONSTRAINT FK_CHUNGCHI_PHIEUDUTHI
	FOREIGN KEY (MAPHIEUDUTHI)
	REFERENCES PHIEUDUTHI(MAPHIEUDUTHI)
GO

ALTER TABLE HOADON
ADD
	CONSTRAINT FK_HOADON_PHIEUDANGKY
	FOREIGN KEY (MAPHIEUDANGKY)
	REFERENCES PHIEUDANGKY(MAPHIEUDANGKY)
	ON DELETE SET NULL,

	CONSTRAINT FK_HOADON_UUDAI
	FOREIGN KEY (MAUUDAI)
	REFERENCES UUDAI(MAUUDAI)
	ON DELETE SET NULL,

	CONSTRAINT FK_HOADON_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL
GO

ALTER TABLE GIAODICHCHUYENKHOAN
ADD
	CONSTRAINT FK_GIAODICHCHUYENKHOAN_THANHTOANHOADON
	FOREIGN KEY (MATHANHTOAN)
	REFERENCES THANHTOANHOADON(MATHANHTOAN)
	ON DELETE SET NULL,

	CONSTRAINT FK_GIAODICHCHUYENKHOAN_KHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL
GO

ALTER TABLE THANHTOANHOADON
ADD
	CONSTRAINT FK_THANHTOANHOADON_HOADON
	FOREIGN KEY (MAHOADON)
	REFERENCES HOADON(MAHOADON)
	ON DELETE SET NULL
GO

ALTER TABLE THANHTOANPHIEUGIAHAN
ADD
	CONSTRAINT FK_THANHTOANPHIEUGIAHAN_PHIEUGIAHAN
	FOREIGN KEY (MAPHIEUGIAHAN)
	REFERENCES PHIEUGIAHAN(MAPHIEUGIAHAN)
	ON DELETE SET NULL
GO

ALTER TABLE PHANCONG
ADD
	CONSTRAINT FK_PHANCONG_LICHTHI
	FOREIGN KEY (MALICHTHI)
	REFERENCES LICHTHI(MALICHTHI)
	ON DELETE NO ACTION,

	CONSTRAINT FK_PHANCONG_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE NO ACTION
GO