
CREATE DATABASE TTNNDB
GO
USE TTNNDB
GO

CREATE TABLE PHIEUGIAHAN
(
	MAPHIEUGIAHAN CHAR(10),
	PHIGIAHAN FLOAT NOT NULL,
	MADANGKY CHAR(10),
	MANHANVIEN CHAR(10),
	TRUONGHOPGIAHAN NVARCHAR(50),

	CONSTRAINT PK_PHIEUGIAHAN
	PRIMARY KEY(MAPHIEUGIAHAN)
)
GO

CREATE TABLE CHUNGMINHGIAHAN
(
	MAPHIEUCM CHAR(10),
	THOIDIEMGIAHAN DATETIME,
	LYDOGIAHAN NVARCHAR(100),

	CONSTRAINT PK_CHUNGMINHGIAHAN
	PRIMARY KEY(MAPHIEUCM)
)
GO

CREATE TABLE DONVICHAMTHI
(
	MADONVI CHAR(10),
	TENDONVI NVARCHAR(100),
	DIACHI NVARCHAR(100),
	SĐT CHAR(10),
	EMAIL VARCHAR(100),

	CONSTRAINT PK_DONVICHAMTHI
	PRIMARY KEY(MADONVI)
)
GO

CREATE TABLE PHIEUDANGKY
(
	MAPHIEUDANGKY CHAR(10),
	NGAYDANGKY DATETIME,
	TENTHISINH NVARCHAR(50) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(100),
	SĐT CHAR(10),
	EMAIL VARCHAR(100),
	MAHOADON CHAR(10),
	MAKHACHANG CHAR(10),
	MALICHTHI CHAR(10),
	MANHANVIEN CHAR(10),

	CONSTRAINT PK_PHIEUDANGKY
	PRIMARY KEY(MAPHIEUDANGKY)
)
GO

CREATE TABLE LICHTHI
(
	MALICHTHI CHAR(10),
	NGAYTHI DATE,
	GIOTHI TIME,
	SOLUONGTOIDA INT,
	TRANGTHAI NVARCHAR(30) NOT NULL CHECK (TRANGTHAI IN (N'SCHEDULED', N'COMPLETED', N'CANCELLED')),
	MAPHONG CHAR(10),
	MADANHGIA CHAR(10),
	MADONVI CHAR(10),

	CONSTRAINT PK_LICHTHI
	PRIMARY KEY(MALICHTHI)
)
GO

CREATE TABLE PHIEUDUTHI
(
	MAPHIEUDUTHI CHAR(10),
	SBD CHAR(6),
	TRANGTHAI NVARCHAR(30) NOT NULL CHECK (TRANGTHAI IN (N'COMPLETED',N'ABSENT')),
	NGAYPHATHANH DATE,
	MANHANVIEN CHAR(10),
	MAPHIEUDANGKY CHAR(10),

	CONSTRAINT PK_PHIEUDUTHI
	PRIMARY KEY (MAPHIEUDUTHI)
)
GO

CREATE TABLE LOAIDANHGIANANGLUC
(
	MADANHGIA CHAR(10),
	TENDANHGIA NVARCHAR(50),
	CAPDO NVARCHAR(50),
	MALINHVUC CHAR(10),

	CONSTRAINT PK_LOAIDANHGIANANGLUC
	PRIMARY KEY(MADANHGIA)
)
GO

CREATE TABLE LINHVUC
(
	MALINHVUC CHAR(10),
	TENLINHVUC NVARCHAR(50),

	CONSTRAINT PK_LINHVUC
	PRIMARY KEY(MALINHVUC)
)
GO

CREATE TABLE PHONGTHI
(
	 MAPHONG CHAR(10),
	 TENPHONG NVARCHAR(30),
	 VITRIPHONG NVARCHAR(50),

	 CONSTRAINT PK_PHONGTHI
	 PRIMARY KEY(MAPHONG)
)
GO

CREATE TABLE CHUNGCHI
(
	MACHUNGCHI CHAR(10),
	NGAYCAP DATE,
	KETQUATHI VARCHAR(20),
	TRANGTHAI NVARCHAR(30) NOT NULL CHECK (TRANGTHAI IN(N'RECEIVED', N'PENDING')),
	MAPHIEUDUTHI CHAR(10),
	MAKHACHHANG CHAR(10),
	MANHANVIEN CHAR(10),

	CONSTRAINT PK_CHUNGCHI
	PRIMARY KEY(MACHUNGCHI)
)
GO

CREATE TABLE HOADON
(
	MAHOADON CHAR(10),
	THANHTIEN DECIMAL,
	NGAYLAP DATE,
	SOLUONGTHISINH INT,
	MAUUDAI CHAR(10),
	MANHANVIEN CHAR(10),

	CONSTRAINT PK_MAHOADON
	PRIMARY KEY(MAHOADON)
)
GO

CREATE TABLE UUDAI
(
	MAUUDAI CHAR(10),
	DIEUKIEN INT,
	PHANTRAMKHUYENMAI FLOAT,

	CONSTRAINT PK_UUDAI
	PRIMARY KEY(MAUUDAI)
)
GO

CREATE TABLE GIAODICHCHUYENKHOAN
(
	MAGIAODICH CHAR(10),
	NGAGIAODICH DATE,
	SOTIEN DECIMAL,
	NGAYTHANHTOAN DATE,
	MATHANHTOAN CHAR(10),
	MAKHACHHANG CHAR(10),

	CONSTRAINT PK_GIAODICHCHUYENKHOAN
	PRIMARY KEY(MAGIAODICH)
)
GO

CREATE TABLE THANHTOANHOADON
(
	MATHANHTOAN CHAR(10),
	TRANGTHAI NVARCHAR(30) NOT NULL CHECK (TRANGTHAI IN(N'RECEIVED', N'PENDING')),
	SOTIEN DECIMAL,
	NGAYTHANHTOAN DATE,
	MAHOADON CHAR(10),

	CONSTRAINT PK_THANHTOANHOADON
	PRIMARY KEY(MATHANHTOAN)
)
GO

CREATE TABLE THANHTOANPHIEUGIAHAN
(
	MAGIAHAN CHAR(10),
	TRANGTHAI NVARCHAR(30) NOT NULL CHECK (TRANGTHAI IN(N'RECEIVED', N'PENDING')),
	SOTIEN DECIMAL,
	NGAYTHANHTOAN DATE,
	MAPHIEUGIAHAN CHAR(10),

	CONSTRAINT PK_THANHTOANPHIEUGIAHAN
	PRIMARY KEY(MAGIAHAN)
)
GO

CREATE TABLE PHANCONG
(
	MALICHTHI CHAR(10),
	MANHANVIEN CHAR(10),

	CONSTRAINT PK_PHANCONG
	PRIMARY KEY(MALICHTHI,MANHANVIEN)
)
GO

CREATE TABLE KHACHHANG
(
	MAKHACHHANG CHAR(10),
	TENKHACHHANG NVARCHAR(50),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	SĐT CHAR(10),
	EMAIL VARCHAR(100),
	LOAIKHACHHANG NVARCHAR(30),

	CONSTRAINT PK_KHACHHANG
	PRIMARY KEY(MAKHACHHANG)
)
GO

CREATE TABLE NHANVIEN
(
	MANHANVIEN CHAR(10),
	TENNHANVIEN NVARCHAR(50),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	SĐT CHAR(10),
	EMAIL VARCHAR(100),
	VAITRO NVARCHAR(30),

	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY(MANHANVIEN)
)
GO

