USE TTNNDB
GO

ALTER TABLE PHIEUGIAHAN DROP CONSTRAINT FK_PHIEUGIAHAN_PHIEUDANGKY;
ALTER TABLE PHIEUGIAHAN DROP CONSTRAINT FK_PHIEUGIAHAN_NHANVIEN;

ALTER TABLE CHUNGMINHGIAHAN DROP CONSTRAINT FK_CHUNGMINHGIAHAN_PHIEUGIAHAN;

ALTER TABLE PHIEUDANGKY DROP CONSTRAINT FK_PHIEUDANGKY_HOADON;
ALTER TABLE PHIEUDANGKY DROP CONSTRAINT FK_PHIEUDANGKY_KHACHHANG;
ALTER TABLE PHIEUDANGKY DROP CONSTRAINT FK_PHIEUDANGKY_LICHTHI;
ALTER TABLE PHIEUDANGKY DROP CONSTRAINT FK_PHIEUDANGKY_NHANVIEN;

ALTER TABLE LICHTHI DROP CONSTRAINT FK_LICHTHI_PHONGTHI;
ALTER TABLE LICHTHI DROP CONSTRAINT FK_LICHTHI_LOAIDANHGIANANGLUC;
ALTER TABLE LICHTHI DROP CONSTRAINT FK_LICHTHI_DONVICHAMTHI;

ALTER TABLE PHIEUDUTHI DROP CONSTRAINT FK_PHIEUDUTHI_NHANVIEN;
ALTER TABLE PHIEUDUTHI DROP CONSTRAINT FK_PHIEUDUTHI_PHIEUDANGKY;

ALTER TABLE LOAIDANHGIANANGLUC DROP CONSTRAINT FK_LOAIDANHGIANANGLUC_LINHVUC;

ALTER TABLE CHUNGCHI DROP CONSTRAINT FK_CHUNGCHI_KHACHHANG;
ALTER TABLE CHUNGCHI DROP CONSTRAINT FK_CHUNGCHI_NHANVIEN;
ALTER TABLE CHUNGCHI DROP CONSTRAINT FK_CHUNGCHI_PHIEUDUTHI;

ALTER TABLE HOADON DROP CONSTRAINT FK_HOADON_UUDAI;
ALTER TABLE HOADON DROP CONSTRAINT FK_HOADON_NHANVIEN;

ALTER TABLE GIAODICHCHUYENKHOAN DROP CONSTRAINT FK_GIAODICHCHUYENKHOAN_THANHTOANHOADON;
ALTER TABLE GIAODICHCHUYENKHOAN DROP CONSTRAINT FK_GIAODICHCHUYENKHOAN_KHACHHANG;

ALTER TABLE THANHTOANHOADON DROP CONSTRAINT FK_THANHTOANHOADON_HOADON;

ALTER TABLE THANHTOANPHIEUGIAHAN DROP CONSTRAINT FK_THANHTOANPHIEUGIAHAN_PHIEUGIAHAN;

ALTER TABLE PHANCONG DROP CONSTRAINT FK_PHANCONG_LICHTHI;
ALTER TABLE PHANCONG DROP CONSTRAINT FK_PHANCONG_NHANVIEN;

GO