USE TTNNDB
GO

-- Tính số tiền trong hóa đơn
CREATE PROCEDURE TINH_TIEN_HOADON
    @MAPHIEUDANGKY CHAR(10)
AS
BEGIN
    DECLARE @SOLUONGTHISINH INT
    DECLARE @GIAHIENTAI INT
    DECLARE @THANHTIEN DECIMAL
    DECLARE @MAHOADON CHAR(10)

    SELECT @SOLUONGTHISINH = COUNT(*)
    FROM THISINH
    WHERE MAPHIEUDANGKY = @MAPHIEUDANGKY

    SELECT @GIAHIENTAI = GIAHIENTAI
    FROM LICHTHI L 
    JOIN PHIEUDANGKY PDK ON PDK.MALICHTHI = L.MALICHTHI
    JOIN LOAIDANHGIANANGLUC LNL ON LNL.MADANHGIA = L.MADANHGIA
    WHERE PDK.MAPHIEUDANGKY = @MAPHIEUDANGKY

    SET @MAHOADON = LEFT(CONVERT(CHAR(36), NEWID()), 10)

    SET @THANHTIEN = @SOLUONGTHISINH * @GIAHIENTAI

    INSERT INTO HOADON (MAHOADON, THANHTIEN, NGAYLAP, SOLUONGTHISINH, MAPHIEUDANGKY)
    VALUES (@MAHOADON, @THANHTIEN, GETDATE(), @SOLUONGTHISINH, @MAPHIEUDANGKY)
END

EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000008'