USE TTNNDB
GO

-- Tính số tiền trong hóa đơn
CREATE PROCEDURE TINH_TIEN_HOADON
    @MAPHIEUDANGKY CHAR(10)
AS
BEGIN
    DECLARE @SOLUONGTHISINH INT
    DECLARE @GIAHIENTAI INT
    DECLARE @THANHTIEN DECIMAL
    DECLARE @MAHOADON CHAR(10)
    DECLARE @PHANTRAMKHUYENMAI FLOAT
    DECLARE @DIEUKIEN INT
    DECLARE @MAHOADON_MAX CHAR(10)
    DECLARE @SO_TIEP INT
    DECLARE @MAHOADON_SOSANH VARCHAR(10)
	DECLARE @MAUUDAI CHAR(10)

    SELECT @SOLUONGTHISINH = COUNT(*)
    FROM THISINH
    WHERE MAPHIEUDANGKY = @MAPHIEUDANGKY

    SELECT @GIAHIENTAI = GIAHIENTAI
    FROM LICHTHI L 
    JOIN PHIEUDANGKY PDK ON PDK.MALICHTHI = L.MALICHTHI
    JOIN LOAIDANHGIANANGLUC LNL ON LNL.MADANHGIA = L.MADANHGIA
    WHERE PDK.MAPHIEUDANGKY = @MAPHIEUDANGKY

    -- Lấy mã hóa đơn lớn nhất
    SELECT @MAHOADON_MAX = MAX(MAHOADON)
    FROM HOADON

    IF @MAHOADON_MAX IS NOT NULL
    BEGIN
        SET @MAHOADON_SOSANH = REPLACE(@MAHOADON_MAX, 'HD', '')
        SET @SO_TIEP = CASE 
                        WHEN ISNUMERIC(@MAHOADON_SOSANH) = 1 THEN CAST(@MAHOADON_SOSANH AS INT) + 1
                        ELSE 1 
                      END
    END
    ELSE
    BEGIN
        SET @SO_TIEP = 1
    END

    SET @MAHOADON = 'HD' + RIGHT('0000000' + CAST(@SO_TIEP AS VARCHAR(7)), 7)

    SELECT @DIEUKIEN = DIEUKIEN, @PHANTRAMKHUYENMAI = PHANTRAMKHUYENMAI, @MAUUDAI = MAUUDAI
    FROM UUDAI
    WHERE DIEUKIEN <= @SOLUONGTHISINH

    SET @THANHTIEN = @SOLUONGTHISINH * @GIAHIENTAI

    IF @DIEUKIEN <= @SOLUONGTHISINH
    BEGIN
        
        SET @THANHTIEN = @THANHTIEN * (1 - @PHANTRAMKHUYENMAI / 100)
    END

    INSERT INTO HOADON (MAHOADON, THANHTIEN, NGAYLAP, SOLUONGTHISINH, MAPHIEUDANGKY, MAUUDAI)
    VALUES (@MAHOADON, @THANHTIEN, GETDATE(), @SOLUONGTHISINH, @MAPHIEUDANGKY, @MAUUDAI)
END

EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000001'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000002'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000003'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000004'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000005'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000006'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000007'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000008'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000009'
EXEC TINH_TIEN_HOADON @MAPHIEUDANGKY = 'PDK0000010'


SELECT*
FROM HOADON

SELECT*
FROM GIAODICHCHUYENKHOAN

SELECT*
FROM PHIEUDANGKY

SELECT*
FROM THANHTOANHOADON

